/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SpendingInsightsRouteImport } from './routes/spending-insights'
import { Route as SmeLedgerRouteImport } from './routes/sme-ledger'
import { Route as SalaryCalculatorRouteImport } from './routes/salary-calculator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FinancialLiteracyRouteImport } from './routes/financial-literacy'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DebtDashboardRouteImport } from './routes/debt-dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BudgetingToolRouteImport } from './routes/budgeting-tool'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingInsightsRoute = SpendingInsightsRouteImport.update({
  id: '/spending-insights',
  path: '/spending-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SmeLedgerRoute = SmeLedgerRouteImport.update({
  id: '/sme-ledger',
  path: '/sme-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryCalculatorRoute = SalaryCalculatorRouteImport.update({
  id: '/salary-calculator',
  path: '/salary-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialLiteracyRoute = FinancialLiteracyRouteImport.update({
  id: '/financial-literacy',
  path: '/financial-literacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtDashboardRoute = DebtDashboardRouteImport.update({
  id: '/debt-dashboard',
  path: '/debt-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetingToolRoute = BudgetingToolRouteImport.update({
  id: '/budgeting-tool',
  path: '/budgeting-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/budgeting-tool': typeof BudgetingToolRoute
  '/contact': typeof ContactRoute
  '/debt-dashboard': typeof DebtDashboardRoute
  '/feedback': typeof FeedbackRoute
  '/financial-literacy': typeof FinancialLiteracyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/salary-calculator': typeof SalaryCalculatorRoute
  '/sme-ledger': typeof SmeLedgerRoute
  '/spending-insights': typeof SpendingInsightsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/budgeting-tool': typeof BudgetingToolRoute
  '/contact': typeof ContactRoute
  '/debt-dashboard': typeof DebtDashboardRoute
  '/feedback': typeof FeedbackRoute
  '/financial-literacy': typeof FinancialLiteracyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/salary-calculator': typeof SalaryCalculatorRoute
  '/sme-ledger': typeof SmeLedgerRoute
  '/spending-insights': typeof SpendingInsightsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/budgeting-tool': typeof BudgetingToolRoute
  '/contact': typeof ContactRoute
  '/debt-dashboard': typeof DebtDashboardRoute
  '/feedback': typeof FeedbackRoute
  '/financial-literacy': typeof FinancialLiteracyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/salary-calculator': typeof SalaryCalculatorRoute
  '/sme-ledger': typeof SmeLedgerRoute
  '/spending-insights': typeof SpendingInsightsRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/budgeting-tool'
    | '/contact'
    | '/debt-dashboard'
    | '/feedback'
    | '/financial-literacy'
    | '/pricing'
    | '/privacy'
    | '/salary-calculator'
    | '/sme-ledger'
    | '/spending-insights'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/budgeting-tool'
    | '/contact'
    | '/debt-dashboard'
    | '/feedback'
    | '/financial-literacy'
    | '/pricing'
    | '/privacy'
    | '/salary-calculator'
    | '/sme-ledger'
    | '/spending-insights'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/budgeting-tool'
    | '/contact'
    | '/debt-dashboard'
    | '/feedback'
    | '/financial-literacy'
    | '/pricing'
    | '/privacy'
    | '/salary-calculator'
    | '/sme-ledger'
    | '/spending-insights'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BudgetingToolRoute: typeof BudgetingToolRoute
  ContactRoute: typeof ContactRoute
  DebtDashboardRoute: typeof DebtDashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  FinancialLiteracyRoute: typeof FinancialLiteracyRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SalaryCalculatorRoute: typeof SalaryCalculatorRoute
  SmeLedgerRoute: typeof SmeLedgerRoute
  SpendingInsightsRoute: typeof SpendingInsightsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending-insights': {
      id: '/spending-insights'
      path: '/spending-insights'
      fullPath: '/spending-insights'
      preLoaderRoute: typeof SpendingInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sme-ledger': {
      id: '/sme-ledger'
      path: '/sme-ledger'
      fullPath: '/sme-ledger'
      preLoaderRoute: typeof SmeLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-calculator': {
      id: '/salary-calculator'
      path: '/salary-calculator'
      fullPath: '/salary-calculator'
      preLoaderRoute: typeof SalaryCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-literacy': {
      id: '/financial-literacy'
      path: '/financial-literacy'
      fullPath: '/financial-literacy'
      preLoaderRoute: typeof FinancialLiteracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debt-dashboard': {
      id: '/debt-dashboard'
      path: '/debt-dashboard'
      fullPath: '/debt-dashboard'
      preLoaderRoute: typeof DebtDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgeting-tool': {
      id: '/budgeting-tool'
      path: '/budgeting-tool'
      fullPath: '/budgeting-tool'
      preLoaderRoute: typeof BudgetingToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BudgetingToolRoute: BudgetingToolRoute,
  ContactRoute: ContactRoute,
  DebtDashboardRoute: DebtDashboardRoute,
  FeedbackRoute: FeedbackRoute,
  FinancialLiteracyRoute: FinancialLiteracyRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SalaryCalculatorRoute: SalaryCalculatorRoute,
  SmeLedgerRoute: SmeLedgerRoute,
  SpendingInsightsRoute: SpendingInsightsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
