/** @type {import('jest').Config} */
module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>"],
  setupFiles: ["<rootDir>/jest.setup.js"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
  },
  testMatch: [
    "**/calculators/__tests__/**/*.test.ts",
    "**/stores/__tests__/**/*.test.ts",
    "**/utils/__tests__/**/*.test.ts",
    "**/components/features/vitals/__tests__/**/*.test.ts",
  ],
  collectCoverageFrom: [
    "calculators/**/*.ts",
    "!calculators/index.ts",
    "!calculators/__tests__/**",
    "components/features/vitals/utils.ts",
    "components/features/vitals/budgetTemplates.ts",
    "utils/**/*.ts",
    "!utils/__tests__/**",
    "!utils/supabase.ts",
    "!utils/logger.ts",
    "!utils/cn.ts",
    "!utils/analytics.ts",
    "!utils/auth.ts",
    "!utils/budgetSync.ts",
    "!utils/budgetStorage.ts",
    "!utils/budgetHydrate.ts",
    "!utils/budgetHydrateSession.ts",
    "!utils/spendingPatterns.ts",
    "!utils/profileVitals.ts",
    "!utils/categoryIconStorage.ts",
    "!utils/tourStorage.ts",
    "!utils/requireFreshAuth.ts",
    "!utils/connectivity.ts",
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
};
