/**
 * Canonical lesson registry — 34 lessons across 7 modules
 * Phase 8: Full curriculum per FRD §30
 *
 * Lesson IDs follow pattern: mod{NN}-{topic}-{NN}
 * Existing IDs preserved for backward compatibility.
 */

import type { Lesson, LessonDifficulty, LessonModule } from "@/types/literacy";

export type LessonDef = Omit<Lesson, "sources" | "verified_by"> & {
  sources: { organization: string; snapshot_id?: string; url?: string }[];
  verified_by: { name: string; credential: string } | null;
};

export const LESSON_DEFS: LessonDef[] = [
  // ── MOD-01: Understanding Your Money (5 lessons) ───────────────────────────
  {
    id: "mod01-budgeting-01",
    title: "Build Your First Monthly Budget",
    module: "MOD-01",
    difficulty: "beginner",
    duration_minutes: 12,
    languages: ["en"],
    tags: ["budget", "saving", "planning", "foundational"],
    content_url: null,
    calculator_id: "budget-builder-v1",
    sources: [
      {
        organization: "Bank of Ghana Financial Literacy Programme",
        url: "https://www.bog.gov.gh",
      },
    ],
    verified_by: null,
    version: "1.1.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod01-budgeting-02",
    title: "The 50/30/20 Rule Explained",
    module: "MOD-01",
    difficulty: "beginner",
    duration_minutes: 10,
    languages: ["en"],
    tags: ["budget", "needs", "wants", "savings", "50-30-20"],
    content_url: null,
    calculator_id: null,
    sources: [
      {
        organization: "Bank of Ghana Financial Literacy Programme",
        url: "https://www.bog.gov.gh",
      },
    ],
    verified_by: null,
    version: "1.1.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod01-budgeting-03",
    title: "Tracking Your Spending",
    module: "MOD-01",
    difficulty: "beginner",
    duration_minutes: 15,
    languages: ["en"],
    tags: ["budget", "tracking", "expenses", "habits"],
    content_url: null,
    calculator_id: null,
    sources: [
      {
        organization: "Bank of Ghana Financial Literacy Programme",
        url: "https://www.bog.gov.gh",
      },
    ],
    verified_by: null,
    version: "1.1.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod01-savings-01",
    title: "Saving: From Susu to Savings Accounts",
    module: "MOD-01",
    difficulty: "beginner",
    duration_minutes: 10,
    languages: ["en"],
    tags: ["savings", "susu", "rosca", "bank", "informal"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "Bank of Ghana", url: "https://www.bog.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod01-savings-02",
    title: "Emergency Funds & Financial Resilience",
    module: "MOD-01",
    difficulty: "beginner",
    duration_minutes: 10,
    languages: ["en"],
    tags: ["emergency fund", "safety net", "3-6 months", "resilience"],
    content_url: null,
    calculator_id: "savings-goal-v1",
    sources: [
      {
        organization: "Bank of Ghana Financial Stability Report",
        url: "https://www.bog.gov.gh",
      },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },

  // ── MOD-02: Tax & Pension (5 lessons) ───────────────────────────────────────
  {
    id: "mod02-tax-01",
    title: "The Ghana Revenue Authority and You",
    module: "MOD-02",
    difficulty: "intermediate",
    duration_minutes: 8,
    languages: ["en"],
    tags: ["gra", "tax", "tin", "registration"],
    content_url: null,
    calculator_id: null,
    sources: [
      {
        organization: "Ghana Revenue Authority",
        url: "https://www.gra.gov.gh",
      },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod02-tax-02",
    title: "PAYE Deep Dive — 2026 Tax Bands",
    module: "MOD-02",
    difficulty: "intermediate",
    duration_minutes: 18,
    languages: ["en"],
    tags: ["paye", "income tax", "tax bands", "gra"],
    content_url: null,
    calculator_id: "paye-ssnit-v1",
    sources: [
      { organization: "GRA — PAYE Guidelines", url: "https://www.gra.gov.gh" },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod02-tax-03",
    title: "SSNIT: Your Pension Foundation",
    module: "MOD-02",
    difficulty: "intermediate",
    duration_minutes: 18,
    languages: ["en"],
    tags: ["ssnit", "pension", "tier 1", "retirement"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "SSNIT Ghana", url: "https://www.ssnit.org.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod02-tax-04",
    title: "Tax Reliefs You Can Claim",
    module: "MOD-02",
    difficulty: "intermediate",
    duration_minutes: 15,
    languages: ["en"],
    tags: ["tax relief", "deductions", "gra"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "GRA", url: "https://www.gra.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod02-tax-05",
    title: "VAT for SME Owners",
    module: "MOD-02",
    difficulty: "intermediate",
    duration_minutes: 16,
    languages: ["en"],
    tags: ["vat", "sme", "business", "gra"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "GRA — VAT", url: "https://www.gra.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },

  // ── MOD-03: Investing (6 lessons) ───────────────────────────────────────────
  {
    id: "mod03-invest-01",
    title: "The Risk-Return Spectrum",
    module: "MOD-03",
    difficulty: "intermediate",
    duration_minutes: 12,
    languages: ["en"],
    tags: ["risk", "return", "investment", "diversification"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "SEC Ghana", url: "https://sec.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod03-invest-02",
    title: "Treasury Bills (T-Bills)",
    module: "MOD-03",
    difficulty: "intermediate",
    duration_minutes: 15,
    languages: ["en"],
    tags: ["t-bill", "treasury", "government", "investment"],
    content_url: null,
    calculator_id: "tbill-simulator-v1",
    sources: [
      {
        organization: "Bank of Ghana — Treasury Markets",
        url: "https://www.bog.gov.gh",
      },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod03-invest-03",
    title: "Government Bonds",
    module: "MOD-03",
    difficulty: "intermediate",
    duration_minutes: 12,
    languages: ["en"],
    tags: ["bonds", "government", "fixed income"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "Bank of Ghana", url: "https://www.bog.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod03-invest-04",
    title: "Mutual Funds & Collective Investment Schemes",
    module: "MOD-03",
    difficulty: "intermediate",
    duration_minutes: 15,
    languages: ["en"],
    tags: ["mutual fund", "cis", "investment", "sec"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "SEC Ghana", url: "https://sec.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod03-invest-05",
    title: "Ghana Stock Exchange Basics",
    module: "MOD-03",
    difficulty: "intermediate",
    duration_minutes: 18,
    languages: ["en"],
    tags: ["gse", "stocks", "shares", "equity"],
    content_url: null,
    calculator_id: null,
    sources: [
      { organization: "Ghana Stock Exchange", url: "https://www.gse.com.gh" },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod03-invest-06",
    title: "Insurance in Ghana",
    module: "MOD-03",
    difficulty: "intermediate",
    duration_minutes: 13,
    languages: ["en"],
    tags: ["insurance", "nic", "protection"],
    content_url: null,
    calculator_id: null,
    sources: [
      {
        organization: "National Insurance Commission",
        url: "https://www.nicgh.org",
      },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },

  // ── MOD-04: Mobile Money (4 lessons) ────────────────────────────────────────
  {
    id: "mod04-mobile-01",
    title: "Mobile Money: Ghana's Financial Revolution",
    module: "MOD-04",
    difficulty: "beginner",
    duration_minutes: 10,
    languages: ["en"],
    tags: ["mobile money", "momo", "mtn", "vodafone", "digital"],
    content_url: null,
    calculator_id: null,
    sources: [
      {
        organization: "Bank of Ghana Payment Systems",
        url: "https://www.bog.gov.gh",
      },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod04-mobile-02",
    title: "Mobile Money Safety & Fraud Prevention",
    module: "MOD-04",
    difficulty: "beginner",
    duration_minutes: 12,
    languages: ["en"],
    tags: ["mobile money", "security", "fraud", "pin", "otp"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "Bank of Ghana", url: "https://www.bog.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod04-mobile-03",
    title: "Mobile Money Savings vs. Bank Savings",
    module: "MOD-04",
    difficulty: "beginner",
    duration_minutes: 11,
    languages: ["en"],
    tags: ["mobile money", "savings", "bank", "comparison"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "Bank of Ghana", url: "https://www.bog.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod04-mobile-04",
    title: "Digital Credit & Borrowing Wisely",
    module: "MOD-04",
    difficulty: "intermediate",
    duration_minutes: 12,
    languages: ["en"],
    tags: ["digital credit", "loans", "mobile money", "borrowing"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "Bank of Ghana", url: "https://www.bog.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },

  // ── MOD-05: SME Finance (6 lessons) ─────────────────────────────────────────
  {
    id: "mod05-sme-01",
    title: "Separating Personal and Business Finances",
    module: "MOD-05",
    difficulty: "intermediate",
    duration_minutes: 12,
    languages: ["en"],
    tags: ["sme", "business", "finances", "separation"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "GEA Ghana", url: "https://gea.org.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod05-sme-02",
    title: "Cash Flow Management for Ghanaian SMEs",
    module: "MOD-05",
    difficulty: "intermediate",
    duration_minutes: 20,
    languages: ["en"],
    tags: ["cash flow", "sme", "management", "business"],
    content_url: null,
    calculator_id: "cash-flow-tool-v1",
    sources: [{ organization: "GEA Ghana", url: "https://gea.org.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod05-sme-03",
    title: "Pricing for Profit",
    module: "MOD-05",
    difficulty: "intermediate",
    duration_minutes: 18,
    languages: ["en"],
    tags: ["pricing", "profit", "sme", "business"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "GEA Ghana", url: "https://gea.org.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod05-sme-04",
    title: "Business Credit and Financing",
    module: "MOD-05",
    difficulty: "advanced",
    duration_minutes: 20,
    languages: ["en"],
    tags: ["business credit", "financing", "loans", "sme"],
    content_url: null,
    calculator_id: "loan-amortization-v1",
    sources: [{ organization: "Bank of Ghana", url: "https://www.bog.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod05-sme-05",
    title: "Tax Compliance for SMEs",
    module: "MOD-05",
    difficulty: "intermediate",
    duration_minutes: 20,
    languages: ["en"],
    tags: ["tax", "sme", "gra", "compliance"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "GRA", url: "https://www.gra.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod05-sme-06",
    title: "Business Insurance and Risk Management",
    module: "MOD-05",
    difficulty: "advanced",
    duration_minutes: 15,
    languages: ["en"],
    tags: ["insurance", "business", "risk", "nic"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "NIC Ghana", url: "https://www.nicgh.org" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },

  // ── MOD-06: Retirement Planning (5 lessons) ──────────────────────────────────
  {
    id: "mod06-retirement-01",
    title: "Why Start Retirement Planning Now",
    module: "MOD-06",
    difficulty: "intermediate",
    duration_minutes: 12,
    languages: ["en"],
    tags: ["retirement", "planning", "pension", "future"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "NPRA Ghana", url: "https://www.npra.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod06-retirement-02",
    title: "Maximising Your SSNIT Tier 1 & 2",
    module: "MOD-06",
    difficulty: "intermediate",
    duration_minutes: 15,
    languages: ["en"],
    tags: ["ssnit", "tier 1", "tier 2", "pension", "npra"],
    content_url: null,
    calculator_id: null,
    sources: [
      { organization: "SSNIT / NPRA", url: "https://www.ssnit.org.gh" },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod06-retirement-03",
    title: "Tier 3 Voluntary Pension",
    module: "MOD-06",
    difficulty: "intermediate",
    duration_minutes: 15,
    languages: ["en"],
    tags: ["tier 3", "voluntary", "pension", "npra", "tax relief"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "NPRA Ghana", url: "https://www.npra.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod06-retirement-04",
    title: "Non-Pension Retirement Assets",
    module: "MOD-06",
    difficulty: "advanced",
    duration_minutes: 15,
    languages: ["en"],
    tags: ["retirement", "t-bills", "property", "investments"],
    content_url: null,
    calculator_id: null,
    sources: [{ organization: "SEC Ghana", url: "https://sec.gov.gh" }],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod06-retirement-05",
    title: "Succession Planning & Wills",
    module: "MOD-06",
    difficulty: "advanced",
    duration_minutes: 13,
    languages: ["en"],
    tags: ["succession", "will", "estate", "inheritance"],
    content_url: null,
    calculator_id: null,
    sources: [
      { organization: "Laws of Ghana", url: "https://laws.ghanalegal.com" },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },

  // ── MOD-07: Consumer Protection & Fraud (3 lessons) ──────────────────────────
  {
    id: "mod07-fraud-01",
    title: "Common Financial Scams in Ghana",
    module: "MOD-07",
    difficulty: "beginner",
    duration_minutes: 12,
    languages: ["en"],
    tags: ["fraud", "scams", "ponzi", "419", "protection"],
    content_url: null,
    calculator_id: null,
    sources: [
      {
        organization: "Bank of Ghana Fraud Report",
        url: "https://www.bog.gov.gh",
      },
      { organization: "SEC Ghana", url: "https://sec.gov.gh" },
    ],
    verified_by: null,
    version: "1.1.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod07-fraud-02",
    title: "Consumer Rights in Ghana's Financial Sector",
    module: "MOD-07",
    difficulty: "beginner",
    duration_minutes: 12,
    languages: ["en"],
    tags: ["consumer rights", "complaints", "bank of ghana", "protection"],
    content_url: null,
    calculator_id: null,
    sources: [
      {
        organization: "Bank of Ghana Consumer Protection",
        url: "https://www.bog.gov.gh",
      },
    ],
    verified_by: null,
    version: "1.1.0",
    last_updated: "2026-02-17",
  },
  {
    id: "mod07-fraud-03",
    title: "Financial Data Privacy & Security",
    module: "MOD-07",
    difficulty: "beginner",
    duration_minutes: 11,
    languages: ["en"],
    tags: ["privacy", "security", "data", "fraud prevention"],
    content_url: null,
    calculator_id: null,
    sources: [
      {
        organization: "Data Protection Commission Ghana",
        url: "https://www.dpca.gov.gh",
      },
    ],
    verified_by: null,
    version: "1.0.0",
    last_updated: "2026-02-17",
  },
];

/** Map lesson ID → Lesson (for useLessons fallback) */
export const LESSON_MAP: Record<string, Lesson> = Object.fromEntries(
  LESSON_DEFS.map((d) => [
    d.id,
    {
      id: d.id,
      title: d.title,
      module: d.module as LessonModule,
      difficulty: d.difficulty as LessonDifficulty,
      duration_minutes: d.duration_minutes,
      languages: d.languages,
      tags: d.tags,
      content_url: d.content_url,
      calculator_id: d.calculator_id,
      sources: d.sources,
      verified_by: d.verified_by,
      version: d.version,
      last_updated: d.last_updated,
    },
  ])
);
